---
title: "Titanic"
author: "Rui La"
date: "11/27/2016"
output: html_document
---

```{r}
library(ggplot2)
library(randomForest)
getwd()
```

load data
```{r, cache=TRUE}
set.seed(1)
train = read.csv("./data/train.csv", stringsAsFactors = FALSE)
test = read.csv("./data/test.csv", stringsAsFactors = FALSE)
genderclassM = read.csv("./data/genderclassmodel.csv", stringsAsFactors = FALSE)
genderM = read.csv("./data/gendermodel.csv", stringsAsFactors = FALSE)
```

extract features and preprocessing

```{r}
extractFeatures <- function(data) {
  features <- c("Pclass",
                "Age",
                "Sex",
                "Parch",
                "SibSp",
                "Fare",
                "Embarked")
       fea <- data[,features]
        fea$Age[is.na(fea$Age)] <- -1
        fea$Fare[is.na(fea$Fare)] <- median(fea$Fare, na.rm=TRUE)
        fea$Embarked[fea$Embarked == ""] <- "S"
        fea$Sex <- as.factor(fea$Sex)
        fea$Embarked <- as.factor(fea$Embarked)
        return(fea)
}
```
Fit the model to the randomforest 

```{r}
##don't know what is ntree and importance in randomForest()
rf = randomForest(extractFeatures(train), as.factor(train$Survived), ntree = 100, importance = TRUE)
```

prediction using test dataset
```{r}
submission = data.frame(PassengerId = test$PassengerId)
submission$Survived = predict (rf, extractFeatures(test))

```
list importance of different variables
```{r}
imp = importance (rf, type = 1)
featureImportance = data.frame(Feature = row.names(imp), Importance = imp[,1])
```

```{r}
p = ggplot (featureImportance, aes(x = reorder(Feature, Importance), y = Importance)) +
        geom_bar(stat="identity", fill = "#53cfff") +
         coord_flip() + #flip coord
         theme_light(base_size = 20) + 
        xlab("") +
        ylab("Importance") + 
        ggtitle("Random Forest Feature Importance\n") +
        theme(plot.title = element_text(size = 18))
p
```


